#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDB_SDRPlay                             39995
#define IDD_ADVANCED                            39996
#define IDC_PPM                                 39997
#define IDC_GAINSLIDER                          39998
#define IDD_SDRPLAY_SETTINGS                    39999
#define IDC_ADVANCED_EXIT                       40000
#define IDC_PROFILE_CHANGED                     41001
#define IDC_LNAGRNO                             41002
#define IDC_LOWARNING                           41003
#define IDC_SETPOINT                            41004
#define IDC_LO120                               41005
#define IDC_ONESHOT                             41006
#define IDC_ADVANCED_APPLY                      41007
#define IDC_TRACKINGPERIOD                      41008
#define IDC_GR                                  41009
#define IDC_TRACKTIME                           41010
#define IDC_PERIODIC                            41011
#define IDC_LO144                               40010
#define IDC_CONTINUOUS                          40011
#define IDC_LOWARNING1                          40013
#define IDC_LO168                               40014
#define IDC_IFMODE                              40015
#define IDC_REFRESH                             40016
#define IDC_LOAUTO                              40017
#define IDC_IFBW                                40018
#define IDC_DCSTAT                              40019
#define IDC_SETPOINT_S                          40021
#define IDC_RSPAGC                              40022
#define IDC_Advanced                            40023
#define IDC_LoadDefaults                        40025
#define IDC_EXIT                                40026
#define IDC_LNASTATE                            40027
#define IDC_LNAGR                               40028
#define IDC_IFGR                                40029
#define IDC_SAMPLERATE                          40032
#define IDC_LoadProfile                         40033
#define IDC_SaveProfile                         40034
#define IDC_ProfileFileName                     40035
#define IDC_STATIC2                             40036
#define IDC_STATIC3                             40038
#define IDC_PPM_S                               40043
#define ID_REFREASH                             40044
#define ID_COMPENSATION                         40045
#define IDC_POSTDCOFFSET                        40046
#define ID_TUNER_COMPENSATION                   40047
#define ID_LOPLAN                               40048
#define ID_TRACKING                             40049
#define IDC_LOADPROFILE_P1                      40076
#define IDC_LOADPROFILE_P2                      40077
#define IDC_LOADPROFILE_P3                      40078
#define IDC_LOADPROFILE_P4                      40079
#define IDC_LOADPROFILE_P5                      40080
#define IDC_LOADPROFILE_P6                      40081
#define IDC_LOADPROFILE_P7                      40082
#define IDC_LOADPROFILE_P8                      40083
#define IDC_ProfilesButton                      40102
#define IDD_PROFILES_PANEL                      40104
#define IDC_PROF_BACK_ONE                       40121
#define IDC_PROF_BACK_TWO                       40122
#define IDC_PROF_BACK_THREE                     40123
#define IDC_PROF_BACK_FOUR                      40124
#define IDC_PROF_BACK_FIVE                      40125
#define IDC_PROF_BACK_SIX                       40126
#define IDC_PROF_BACK_SEVEN                     40127
#define IDC_PROF_BACK_EIGHT                     40128
#define IDC_PROF_BUTTON_ONE                     40131
#define IDC_PROF_BUTTON_TWO                     40132
#define IDC_PROF_BUTTON_THREE                   40133
#define IDC_PROF_BUTTON_FOUR                    40134
#define IDC_PROF_BUTTON_FIVE                    40135
#define IDC_PROF_BUTTON_SIX                     40136
#define IDC_PROF_BUTTON_SEVEN                   40137
#define IDC_PROF_BUTTON_EIGHT                   40138
#define IDC_PROF_DESC_ONE                       40141
#define IDC_PROF_DESC_TWO                       40142
#define IDC_PROF_DESC_THREE                     40143
#define IDC_PROF_DESC_FOUR                      40144
#define IDC_PROF_DESC_FIVE                      40145
#define IDC_PROF_DESC_SIX                       40146
#define IDC_PROF_DESC_SEVEN                     40147
#define IDC_PROF_DESC_EIGHT                     40148
#define IDC_PROF_EXIT                           40164
#define IDC_HELP_BUTTON                         40169
#define IDD_HELP_PANEL                          40170
#define IDC_HELP_PANEL_EXIT                     40171
#define IDC_HELP_STATIC1                        40172
#define IDC_HELP_STATIC2                        40173
#define IDC_HELP_LINK                           40174
#define IDC_HELP_STATIC3                        40175
#define IDC_HELP_STATIC4                        40176
#define IDC_LNAGR_SWITCH						40178
#define IDC_TOTALGR                             40179
#define IDC_STATIONNAME                         40180
#define IDD_STATION_PANEL                       40181
#define IDC_STATION_LABEL                       40182
#define IDC_StationName_PopOut                  40183
#define IDD_STATIONCONFIG_PANEL                 40184
#define IDC_STATIONCONFIG_ENABLE                40185
#define IDC_STATIONCONFIG_PANEL_EXIT            40186
#define IDC_ADVANCED_STATIONCONFIG              40187
#define IDC_STATIONCONFIG_STATUS                40188
#define IDC_STATIONCONFIG_TAC                   40189
#define IDC_STATIONCONFIG_STATIC1               40190
#define IDC_STATIONCONFIG_ITU                   40191
#define IDC_STATIONCONFIG_STATIC2               40192
#define IDC_STATIONCONFIG_STATIC3               40193
#define IDC_STATIONCONFIG_STATIC4               40199
#define IDC_STATIONCONFIG_OFFLINE               40200
#define IDC_DECIMATION                          40201
#define IDC_FINALSR                             40202
#define IDC_OVERLOAD							40205
#define IDC_APIVER								40206
#define IDC_APIPATH								40207
#define IDC_REGPATH								40208
